# version: "3.8"
services:
  backend-service: 
    container_name: di-backend_container
    build:
      context: ./backend
      target: development
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    # potential bind mount so local changes are reflected in docker container
    # volumes: 
    #   - ./app:/usr/src/app
    #   - /usr/src/app/node_modules
    # links: # apparently depreciated??  
    #   - db:postgress
    depends_on:
      - neo4j-service
    environment:
      PORT: 5001
      SECRET_KEY: "you-will-never-guess"
      ENV_FOR_DYNACONF: docker
  neo4j-service: 
    container_name: di-neo4j_container
    image: neo4j:5.26.0-bullseye
    # potential data mount so data is persistent across containers
    # volumes: 
    #   - database:/data/db
    restart: always
    ports:
      - "7474:7474"  # Neo4j HTTP interface
      - "7687:7687"  # Neo4j Bolt protocol (typically used for database access)
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    secrets:
      - neo4j_auth_file

# volumes:
#   database:
secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt
