global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api: 
  dashboard: true
  insecure: true
entryPoints: 
  web: 
    address: :80 
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  

http:
  routers:
    frontend-service:
      rule: "Host(`dependendyinspection.com`)"
      entryPoints:
        - websecure
      service: "frontend-service"
    backend-service:
      rule: "Host(`dependendyinspection.com/api`)"
      entryPoints:
        - websecure
      service: "backend-service"
      # tls: {}
  # services:
  #   frontend-service:
  #     loadbalancer: 
providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
# certificatesResolvers:
#   myresolver:
#     acme:
#       tlsChallenge:
#         true
#       email: 
#         ngstafford1@gmail.com 
#       storage:
#         /letsencrypt/acme.json
    # exposedByDefault: true
    # network: internal
    

