global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api: 
  dashboard: true
  insecure: true
entryPoints: 
  web: 
    address: :80 
  websecure:
    address: :443

# http:
#   routers:
#     frontend-service:
#       rule: "Host(`localhost`)"
#       entryPoints:
#         - web
#       service: "frontend-service"
#       # tls: {}
#   services:
#     frontend-service:
#       loadbalancer: 
providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    # exposedByDefault: false
    exposedByDefault: true
    # network: internal
    

