[default]
NEO4J_USERNAME = "neo4j"
NEO4J_HOST = "localhost"
NEO4J_DB = "neo4j"
NEO4J_PORT = "7474"
IS_DOCKER = "false"


[development]
NEO4J_HOST = "localhost"

[docker]
NEO4J_HOST = "neo4j-service"
NEO4J_PORT = "7687"
IS_DOCKER = "true"
