[default]
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "your_password"
NEO4J_HOST = "default"
NEO4J_DB = "neo4j"
NEO4J_PORT = "7474"


[development]
# DB_HOST = "localhost"
NEO4J_HOST = "development"

[docker]
# DB_HOST = "db"
NEO4J_HOST = "neo4j-service"
# NEO4J_HOST = "0.0.0.0"
NEO4J_PORT = "7687"
